name: CI

on:
  push:

jobs:
  test:
    name: Run Tests
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Run tests
        run: make test
